services:
  - type: web
    name: ravex-helper
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NODE_VERSION
        value: "20"

  - type: web
    name: ravex-security
    runtime: node
    plan: free
    rootDir: security
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NODE_VERSION
        value: "20"
